"use client";

import React, { useState, useMemo } from 'react';
import { 
    MapPin, 
    Activity, 
    Radio, 
    AlertTriangle, 
    ShieldCheck, 
    Users, 
    Clock, 
    Fuel, 
    Truck, 
    BarChart2, 
    Play, 
    Pause, 
    RotateCcw, 
    Layers, 
    CheckCircle2, 
    Info, 
    Navigation, 
    Tent,
    TrendingUp,
    Crosshair
} from 'lucide-react';

// Master Prompt Event Schema
export interface OperationEvent {
    id: string;
    type: 'EVENT_INCIDENT' | 'EVENT_DEPLOY' | 'EVENT_ALERT' | 'EVENT_STATUS' | 'EVENT_COMM' | 'EVENT_TASK';
    timestamp: string;
    actorId?: string;
    actorName?: string;
    role?: string;
    lat?: number;
    lng?: number;
    coord?: string;
    entityId?: string;
    payload?: any;
    description: string;
    severity?: 'CRITICAL' | 'WARNING' | 'NORMAL';
}

interface KavkasReportViewerProps {
    operation: any;
    reportType: string;
    reportContent: any;
    reportVersion: number;
    generatedAt: string;
}

export default function KavkasReportViewer({ 
    operation, 
    reportType, 
    reportContent, 
    reportVersion, 
    generatedAt 
}: KavkasReportViewerProps) {
    const formattedDate = new Date(generatedAt).toLocaleString('tr-TR');

    // Extract real events from reportContent or operation. Empty if none exist.
    const rawEvents: OperationEvent[] = useMemo(() => {
        if (reportContent?.timeline && Array.isArray(reportContent.timeline)) {
            // Priority: The filtered timeline specific to this report type generated by the backend
            return reportContent.timeline.map((item: any, i: number) => ({
                id: item.id || `tl-${i}`,
                type: item.type || 'EVENT_STATUS',
                timestamp: item.time || item.timestamp || '00:00',
                actorName: item.actor || item.actorName || 'SİSTEM',
                description: item.description || 'Filtrelenmiş Olay',
                severity: item.severity || 'NORMAL',
                coord: item.coord || 'BİLİNMİYOR'
            }));
        }
        if (reportContent?.events && Array.isArray(reportContent.events) && reportContent.events.length > 0) {
            return reportContent.events;
        }
        if (reportContent?.missionLedger && Array.isArray(reportContent.missionLedger) && reportContent.missionLedger.length > 0) {
            return reportContent.missionLedger.map((item: any, i: number) => ({
                id: item.id || `ml-${i}`,
                type: 'EVENT_STATUS',
                timestamp: item.timestamp || item.time || '00:00',
                actorName: item.actor || item.team || 'BİRİM',
                description: item.description || item.action || 'Operasyonel Kayıt',
                severity: item.severity || 'NORMAL',
                coord: item.coord || '35T VK 7200'
            }));
        }
        if (operation?.events && Array.isArray(operation.events) && operation.events.length > 0) {
            return operation.events;
        }
        return []; // Rule 7: Strict compliance - No fake events!
    }, [operation, reportContent]);

    const hasData = rawEvents.length > 0;

    // Timeline Replay Index
    const [replayIndex, setReplayIndex] = useState<number>(hasData ? rawEvents.length - 1 : 0);
    const [isPlaying, setIsPlaying] = useState<boolean>(false);

    React.useEffect(() => {
        let interval: any;
        if (isPlaying && hasData) {
            interval = setInterval(() => {
                setReplayIndex((prev) => {
                    if (prev >= rawEvents.length - 1) {
                        setIsPlaying(false);
                        return prev;
                    }
                    return prev + 1;
                });
            }, 2000);
        }
        return () => clearInterval(interval);
    }, [isPlaying, hasData, rawEvents.length]);

    const activeEvents = useMemo(() => {
        return hasData ? rawEvents.slice(0, replayIndex + 1) : [];
    }, [rawEvents, replayIndex, hasData]);

    const currentEvent = hasData ? (rawEvents[replayIndex] || rawEvents[rawEvents.length - 1]) : null;

    // Report Type specific Titles and Focus Badges
    const reportMeta = useMemo(() => {
        const metaMap: Record<string, { title: string; focus: string; tagColor: string }> = {
            'OPERASYONLAR': {
                title: 'Operasyonlar Grubu (Olay Akışı & Dijital Yeniden İnşa)',
                focus: 'ZAMAN & MEKÂN ODAKLI RAPOR',
                tagColor: 'border-red-500/50 text-red-400 bg-red-500/10'
            },
            'PLANLAMA_SONUC': {
                title: 'Planlama ve Sonuç Grubu (Saha Tarama & Kapsama)',
                focus: 'SEKTÖR VE GRID KAPSAMA ODAKLI RAPOR',
                tagColor: 'border-emerald-500/50 text-emerald-400 bg-emerald-500/10'
            },
            'MUHENDISLIK': {
                title: 'Mühendislik Grubu (Altyapı, Enkaz & Hasar Tespiti)',
                focus: 'ALTYAPI & ENKAZ HASSASİYET RAPORU',
                tagColor: 'border-amber-500/50 text-amber-400 bg-amber-500/10'
            },
            'GUVENLIK': {
                title: 'Güvenlik Grubu (Personel & Saha Emniyeti)',
                focus: 'PERSONEL AKTİF/RÖLANTİ & SAHA EMNİYETİ',
                tagColor: 'border-purple-500/50 text-purple-400 bg-purple-500/10'
            },
            'LOJISTIK': {
                title: 'Lojistik Grubu (Kaynak & Malzeme İkmal Raporu)',
                focus: 'ENVANTER & İKMAL DAĞILIMI',
                tagColor: 'border-blue-500/50 text-blue-400 bg-blue-500/10'
            },
            'US_LOJISTIGI': {
                title: 'Üs Lojistiği (Kamp Alanı & Ana Garaj İkmal Raporu)',
                focus: 'KAMP ALANI & MERKEZ ÜS DÜZENİ',
                tagColor: 'border-cyan-500/50 text-cyan-400 bg-cyan-500/10'
            },
            'ULASTIRMA_ARAC_LOJISTIGI': {
                title: 'Ulaştırma ve Araç Lojistiği (GPS, Mesafe & Yakıt)',
                focus: 'ARAÇ MESAFE & YAKIT VERİMLİLİK RAPORU',
                tagColor: 'border-orange-500/50 text-orange-400 bg-orange-500/10'
            }
        };
        return metaMap[reportType] || {
            title: `${reportType} Operasyonel Raporu`,
            focus: 'GENEL RAPOR',
            tagColor: 'border-neutral-500/50 text-neutral-400 bg-neutral-500/10'
        };
    }, [reportType]);

    return (
        <div className="w-full bg-[#0b0f14] text-neutral-200 p-6 rounded-xl border border-[#1f2937] font-sans flex flex-col gap-6 shadow-2xl relative overflow-hidden">
            
            {/* 🔴 BLOK 1: HEADER & OPERASYON ÖZETİ */}
            <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-[#121821] p-4 rounded-lg border border-[#1f2937]">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-red-600/90 rounded border border-red-500/50 flex items-center justify-center font-black text-xl text-white shadow-[0_0_15px_rgba(220,38,38,0.3)]">
                        M1G
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <span className={`text-[10px] font-mono px-2 py-0.5 rounded border uppercase font-bold tracking-wider ${reportMeta.tagColor}`}>
                                {reportMeta.focus}
                            </span>
                            <span className="text-[10px] text-neutral-500 font-mono">REV-{reportVersion}</span>
                        </div>
                        <h1 className="text-xl font-black uppercase text-white tracking-wide mt-1">
                            {reportMeta.title}
                        </h1>
                        <div className="flex flex-wrap gap-4 text-[11px] text-neutral-400 font-medium mt-1">
                            <span className="flex items-center gap-1"><MapPin size={12} className="text-red-400" /> {operation?.location || 'SEKTÖR / MERKEZ'}</span>
                            <span className="flex items-center gap-1"><Clock size={12} className="text-blue-400" /> {formattedDate}</span>
                            <span className="flex items-center gap-1 text-neutral-500">OP-ID: {operation?.id?.substring(0, 8) || 'OP-2026-X'}</span>
                        </div>
                    </div>
                </div>

                {/* KPI CARDS */}
                <div className="flex gap-3 w-full md:w-auto overflow-x-auto pb-1 md:pb-0">
                    <div className="bg-[#0b0f14] border border-[#1f2937] p-3 rounded min-w-[110px] relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-1 bg-blue-500"></div>
                        <div className="text-[9px] text-neutral-400 font-bold uppercase tracking-wider">KAYITLI EVENT</div>
                        <div className="text-2xl font-black text-white mt-0.5">{rawEvents.length}</div>
                    </div>
                    <div className="bg-[#0b0f14] border border-[#1f2937] p-3 rounded min-w-[110px] relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-1 bg-emerald-500"></div>
                        <div className="text-[9px] text-neutral-400 font-bold uppercase tracking-wider">KAMP ALANI</div>
                        <div className="text-xs font-black text-emerald-400 mt-2 flex items-center gap-1">
                            <Tent size={14} /> KAFKAS ÜSSÜ
                        </div>
                    </div>
                </div>
            </header>

            {/* 🔴 BLOK 2: MEKÂNSAL ANALİZ (HARİTA + TIMELINE REPLAY + KAMP ALANI İŞARETİ) */}
            <section className="bg-[#121821] border border-[#1f2937] rounded-lg p-4 flex flex-col gap-4">
                <div className="flex justify-between items-center border-b border-[#1f2937] pb-3">
                    <div className="flex items-center gap-2">
                        <Crosshair size={16} className="text-red-500" />
                        <h2 className="text-sm font-bold text-white uppercase tracking-wider">
                            MEKÂNSAL REPLAY & KAMP ALANI HARİTASI ({reportType})
                        </h2>
                    </div>
                    {hasData && (
                        <div className="flex items-center gap-3">
                            <button 
                                onClick={() => setIsPlaying(!isPlaying)}
                                className="bg-red-600 hover:bg-red-500 text-white text-xs font-bold px-3 py-1.5 rounded flex items-center gap-1.5 transition-colors"
                            >
                                {isPlaying ? <Pause size={14} /> : <Play size={14} />}
                                {isPlaying ? 'DURAKLAT' : 'REPLAY BAŞLAT'}
                            </button>
                            <button 
                                onClick={() => { setReplayIndex(0); setIsPlaying(false); }}
                                className="bg-[#1f2937] hover:bg-neutral-700 text-neutral-300 text-xs font-medium px-2 py-1.5 rounded"
                            >
                                <RotateCcw size={14} />
                            </button>
                        </div>
                    )}
                </div>

                {/* Map Display Container */}
                <div className="grid grid-cols-1 md:grid-cols-12 gap-4 h-[400px]">
                    {/* Event Log / Report Focus Log Panel */}
                    <div className="md:col-span-4 bg-[#0b0f14] border border-[#1f2937] rounded p-3 flex flex-col h-full overflow-hidden">
                        <div className="flex justify-between items-center border-b border-[#1f2937] pb-2 mb-2">
                            <span className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider flex items-center gap-1">
                                <Radio size={12} className="text-red-400 animate-pulse" /> OLAY & KAYIT AKIŞI ({rawEvents.length})
                            </span>
                        </div>
                        {hasData ? (
                            <div className="flex-1 overflow-y-auto custom-scrollbar space-y-2 pr-1">
                                {rawEvents.map((ev, idx) => {
                                    const isActive = idx <= replayIndex;
                                    const isCurrent = idx === replayIndex;
                                    return (
                                        <div 
                                            key={ev.id}
                                            onClick={() => { setReplayIndex(idx); setIsPlaying(false); }}
                                            className={`p-2.5 rounded border transition-all cursor-pointer text-xs ${
                                                isCurrent 
                                                    ? 'bg-red-950/40 border-red-500/80 text-white shadow-[0_0_10px_rgba(239,68,68,0.2)]' 
                                                    : isActive 
                                                        ? 'bg-[#121821] border-[#1f2937] text-neutral-300 opacity-90' 
                                                        : 'bg-[#0b0f14] border-transparent text-neutral-600 opacity-40'
                                            }`}
                                        >
                                            <div className="flex justify-between items-center mb-1">
                                                <span className="font-mono text-[10px] font-bold text-blue-400">[{ev.timestamp}]</span>
                                                <span className="text-[9px] px-1.5 py-0.5 rounded font-mono bg-blue-500/20 text-blue-400">
                                                    {ev.actorName || 'Saha Kaydı'}
                                                </span>
                                            </div>
                                            <div className="font-medium leading-snug">{ev.description}</div>
                                        </div>
                                    );
                                })}
                            </div>
                        ) : (
                            <div className="flex-1 flex flex-col items-center justify-center p-4 text-center">
                                <Info size={24} className="text-neutral-600 mb-2" />
                                <span className="text-xs font-semibold text-neutral-400">Bu analiz için yeterli veri yok</span>
                                <span className="text-[10px] text-neutral-600 mt-1">Saha kayıtları oluştukça akış burada görünecektir.</span>
                            </div>
                        )}
                    </div>

                    {/* Interactive Tactical Map Component */}
                    <div className="md:col-span-8 bg-[#070a0e] border border-[#1f2937] rounded relative overflow-hidden flex flex-col justify-between p-4">
                        {/* Tactical Grid Overlay */}
                        <div className="absolute inset-0 pointer-events-none opacity-20" style={{ 
                            backgroundImage: 'linear-gradient(to right, #1f2937 1px, transparent 1px), linear-gradient(to bottom, #1f2937 1px, transparent 1px)',
                            backgroundSize: '40px 40px'
                        }}></div>

                        {/* Top HUD */}
                        <div className="relative z-10 flex justify-between items-center text-[10px] font-mono text-neutral-400 bg-[#0b0f14]/80 p-2 rounded border border-[#1f2937] backdrop-blur">
                            <div className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping"></span>
                                <span>TAKTİK HARİTA & KAMP ALANI</span>
                            </div>
                            <div>ODAK SEKTÖR: {operation?.location || 'SEKTÖR ALPHA'}</div>
                        </div>

                        {/* Map Visualizer */}
                        <div className="relative flex-1 my-4 flex items-center justify-center">
                            {/* ⛺ KAMP ALANI İŞARETİ (ZORUNLU FİZİKİ İŞARET) */}
                            <div className="absolute top-[25%] left-[20%] z-30 flex flex-col items-center group">
                                <div className="p-2 bg-emerald-600/90 text-white rounded-lg border border-emerald-400 shadow-[0_0_15px_rgba(16,185,129,0.5)] flex items-center gap-1.5">
                                    <Tent size={16} />
                                    <span className="text-[10px] font-black tracking-wider uppercase">KAFKAS KAMP ALANI</span>
                                </div>
                                <span className="text-[8px] font-mono text-emerald-400 mt-1 bg-black/80 px-1 rounded">MERKEZ LOJİSTİK ÜSSÜ</span>
                            </div>

                            {/* Active Event Pins */}
                            {activeEvents.map((ev, i) => {
                                const offsetX = (i * 50 - 60);
                                const offsetY = ((i % 2) * 60 - 30);
                                return (
                                    <div 
                                        key={ev.id}
                                        style={{ transform: `translate(${offsetX}px, ${offsetY}px)` }}
                                        className="absolute flex flex-col items-center z-20"
                                    >
                                        <div className="p-1.5 rounded-full bg-blue-600 border border-blue-400 text-white shadow-md">
                                            <MapPin size={14} />
                                        </div>
                                        <span className="text-[9px] font-mono font-bold bg-[#0b0f14]/90 text-white px-1.5 py-0.5 rounded border border-[#1f2937] mt-1 whitespace-nowrap">
                                            {ev.actorName || `KAYIT-${i+1}`}
                                        </span>
                                    </div>
                                );
                            })}
                        </div>

                        {/* Bottom Status Overlay */}
                        <div className="relative z-10 bg-[#0b0f14]/90 p-2.5 rounded border border-[#1f2937] flex justify-between items-center text-xs">
                            <div className="flex items-center gap-2">
                                <Tent size={14} className="text-emerald-400" />
                                <span className="text-[11px] font-semibold text-neutral-300">Kamp Alanı & Sahra Üssü İletişimi Aktif</span>
                            </div>
                            <span className="text-[10px] font-mono text-neutral-500">M1G SAHA HARİTASI</span>
                        </div>
                    </div>
                </div>

                {/* Timeline Slider Control (Only if data exists) */}
                {hasData && (
                    <div className="flex flex-col gap-1 bg-[#0b0f14] p-3 rounded border border-[#1f2937]">
                        <div className="flex justify-between text-[10px] font-mono text-neutral-400">
                            <span>İLK KAYIT ({rawEvents[0]?.timestamp})</span>
                            <span className="text-red-400 font-bold">REPLAY İLERLEMESİ ({activeEvents.length}/{rawEvents.length})</span>
                            <span>SON KAYIT ({rawEvents[rawEvents.length - 1]?.timestamp})</span>
                        </div>
                        <input 
                            type="range"
                            min={0}
                            max={rawEvents.length - 1}
                            value={replayIndex}
                            onChange={(e) => {
                                setReplayIndex(Number(e.target.value));
                                setIsPlaying(false);
                            }}
                            className="w-full h-2 bg-[#1f2937] rounded-lg appearance-none cursor-pointer accent-red-500"
                        />
                    </div>
                )}
            </section>

            {/* 🔴 BLOK 3, 4, 5, 6: SEÇİLİ RAPOR TÜRÜNE UYGUN DİNAMİK VE VERİ ODAKLI GRİD */}
            <section className="grid grid-cols-1 md:grid-cols-2 gap-6">

                {/* 5.1 OPERASYON YOĞUNLUĞU */}
                <div className="bg-[#121821] border border-[#1f2937] p-4 rounded-lg flex flex-col justify-between">
                    <div className="border-b border-[#1f2937] pb-2 mb-3 flex justify-between items-center">
                        <h3 className="text-xs font-bold text-white uppercase flex items-center gap-2">
                            <TrendingUp size={14} className="text-blue-400" />
                            5.1 OPERASYON YOĞUNLUĞU (ZAMAN ANALİZİ)
                        </h3>
                    </div>
                    {hasData ? (
                        <div className="space-y-2">
                            {rawEvents.map((ev, i) => (
                                <div key={i} className="flex items-center gap-2 text-[10px] font-mono">
                                    <span className="w-12 text-neutral-400">{ev.timestamp}</span>
                                    <div className="flex-1 bg-[#0b0f14] h-4 rounded overflow-hidden p-0.5 border border-[#1f2937]">
                                        <div 
                                            style={{ width: `${Math.min(100, (i + 1) * 20)}%` }}
                                            className="h-full rounded bg-blue-500"
                                        ></div>
                                    </div>
                                    <span className="w-8 text-right font-bold text-neutral-300">{i + 1} ev</span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="py-8 text-center text-xs text-neutral-500 italic bg-[#0b0f14] p-4 rounded border border-[#1f2937]">
                            Bu analiz için yeterli veri yok
                        </div>
                    )}
                </div>

                {/* 5.2 ALAN KAPSAMA */}
                <div className="bg-[#121821] border border-[#1f2937] p-4 rounded-lg flex flex-col justify-between">
                    <div className="border-b border-[#1f2937] pb-2 mb-3 flex justify-between items-center">
                        <h3 className="text-xs font-bold text-white uppercase flex items-center gap-2">
                            <Layers size={14} className="text-emerald-400" />
                            5.2 ALAN KAPSAMA (SEKTÖR VE GRID ANALİZİ)
                        </h3>
                    </div>
                    {reportContent?.areaCoverage ? (
                        <div className="space-y-3">
                            <div className="grid grid-cols-2 gap-3 text-center">
                                <div className="bg-[#0b0f14] p-3 rounded border border-[#1f2937]">
                                    <div className="text-[10px] text-neutral-400 font-bold">TARANAN ALAN ORANI</div>
                                    <div className="text-xl font-black text-emerald-400 mt-1">
                                        {reportContent.areaCoverage.scannedPercentage || '%0'}
                                    </div>
                                </div>
                                <div className="bg-[#0b0f14] p-3 rounded border border-[#1f2937]">
                                    <div className="text-[10px] text-neutral-400 font-bold">SEKTÖR BILGISI</div>
                                    <div className="text-xl font-black text-amber-400 mt-1">
                                        {reportContent.areaCoverage.criticalSector || 'N/A'}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="py-8 text-center text-xs text-neutral-500 italic bg-[#0b0f14] p-4 rounded border border-[#1f2937]">
                            Bu analiz için yeterli veri yok
                        </div>
                    )}
                </div>

                {/* 5.3 PERSONEL & AKTİF SÜRE */}
                <div className="bg-[#121821] border border-[#1f2937] p-4 rounded-lg flex flex-col justify-between">
                    <div className="border-b border-[#1f2937] pb-2 mb-3 flex justify-between items-center">
                        <h3 className="text-xs font-bold text-white uppercase flex items-center gap-2">
                            <Users size={14} className="text-purple-400" />
                            5.3 PERSONEL & AKTİF SÜRE KULLANIMI
                        </h3>
                    </div>
                    {operation?.teams && operation.teams.length > 0 ? (
                        <div className="space-y-2">
                            {operation.teams.map((team: any, idx: number) => (
                                <div key={idx} className="bg-[#0b0f14] p-2.5 rounded border border-[#1f2937] flex justify-between items-center text-xs">
                                    <div>
                                        <div className="font-bold text-white">{team.name || `TİM ${idx + 1}`}</div>
                                        <div className="text-[10px] text-neutral-400 font-mono">{team.role || 'Arama Kurtarma'}</div>
                                    </div>
                                    <span className="text-emerald-400 font-mono font-bold">AKTİF</span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="py-8 text-center text-xs text-neutral-500 italic bg-[#0b0f14] p-4 rounded border border-[#1f2937]">
                            Bu analiz için yeterli veri yok
                        </div>
                    )}
                </div>

                {/* 5.4 ARAÇ & MESAFA / YAKIT */}
                <div className="bg-[#121821] border border-[#1f2937] p-4 rounded-lg flex flex-col justify-between">
                    <div className="border-b border-[#1f2937] pb-2 mb-3 flex justify-between items-center">
                        <h3 className="text-xs font-bold text-white uppercase flex items-center gap-2">
                            <Truck size={14} className="text-amber-400" />
                            5.4 ARAÇ & MESAFA / YAKIT DEĞERLENDİRMESİ
                        </h3>
                    </div>
                    {reportContent?.vehicleAnalysis ? (
                        <div className="space-y-3">
                            <div className="grid grid-cols-2 gap-3 text-xs font-mono">
                                <div className="bg-[#0b0f14] p-3 rounded border border-[#1f2937]">
                                    <div className="text-[9px] text-neutral-400 font-bold">TOPLAM MESAFA</div>
                                    <div className="text-lg font-black text-white mt-1">{reportContent.vehicleAnalysis.totalKm || '0'} KM</div>
                                </div>
                                <div className="bg-[#0b0f14] p-3 rounded border border-[#1f2937]">
                                    <div className="text-[9px] text-neutral-400 font-bold">TAHMİNİ YAKIT</div>
                                    <div className="text-lg font-black text-amber-400 mt-1">{reportContent.vehicleAnalysis.fuelConsumed || '0'} LT</div>
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="py-8 text-center text-xs text-neutral-500 italic bg-[#0b0f14] p-4 rounded border border-[#1f2937]">
                            Bu analiz için yeterli veri yok
                        </div>
                    )}
                </div>

            </section>

            {/* 🔴 BLOK 6: SONUÇ VE DEĞERLENDİRME METNİ */}
            <section className="bg-[#121821] border border-[#1f2937] p-5 rounded-lg space-y-4">
                <div className="border-b border-[#1f2937] pb-3 flex justify-between items-center">
                    <h3 className="text-xs font-bold text-white uppercase flex items-center gap-2">
                        <CheckCircle2 size={16} className="text-emerald-400" />
                        6. SONUÇ VE DEĞERLENDİRME RAPORU (OPERASYONEL INTELLIGENCE)
                    </h3>
                    <span className="text-[10px] text-emerald-400 font-mono bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/30">
                        DENETLENEBİLİR DİJİTAL İMZA
                    </span>
                </div>

                <div className="bg-[#0b0f14] p-4 rounded border border-[#1f2937] space-y-2">
                    <h4 className="text-xs font-bold text-neutral-300 uppercase flex items-center gap-1.5">
                        <Info size={14} className="text-blue-400" />
                        GENEL OPERASYONEL ÖZET METNİ
                    </h4>
                    <p className="text-xs text-neutral-300 leading-relaxed font-sans">
                        {reportContent?.summary || 
                            `Bu rapor sistem tarafından otomatik olarak ${rawEvents.length} adet Mission Ledger kaydından derlenmiştir.`
                        }
                    </p>
                </div>
            </section>

            {/* Footer Signoff */}
            <footer className="flex justify-between items-center text-[10px] font-mono text-neutral-500 pt-2 border-t border-[#1f2937]">
                <div>M1G KAFKAS REPORTING ENGINE v2.0 • AUTOGENERATED</div>
                <div>CONFIDENTIAL & AUDITABLE OPERATIONAL REPORT</div>
            </footer>
        </div>
    );
}
